{% set name = "scores" %}
{% set version = "2.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scores-{{ version }}.tar.gz
  sha256: 195f5b02d227351b7d6675f04946cf1fe20126321a0fb0fc3c9d5037fa87c62c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - tomlkit
    - pip
  run:
    - python >={{ python_min }}
    - xarray >=2024.1
    - pandas >=2.0,<3.dev0
    - scipy >=1.13,<2.dev0
    - bottleneck >=1.3,<2.dev0

test:
  imports:
    - scores
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: A Python package for verifying and evaluating models and predictions with xarray
  description: |
    scores is a Python package containing mathematical functions for the verification, evaluation
    and optimisation of forecasts, predictions or models. It supports labelled n-dimensional
    (multidimensional) data, which is used in many scientific fields and in machine learning. At
    present, scores primarily supports the geoscience communities; in particular, the meteorological,
    climatological and oceanographic communities.  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://scores.readthedocs.io/
  home: https://github.com/nci/scores

extra:
  recipe-maintainers:
    - tennlee
